:toc:
:toc-title:
:toclevels: 2
:sectnums:

= External Access via AWS Elastic Load Balancers

External access to our EKS Kubernetes cluster is provided via AWS elastic load balancers. The link:https://kubernetes-sigs.github.io/aws-load-balancer-controller[AWS Load Balancer Controller] provisions and manages the following resources:

* An link:https://docs.aws.amazon.com/elasticloadbalancing/latest/application/introduction.html[AWS Application Load Balancer (ALB)] when you create a link:https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Ingress].
* An link:https://docs.aws.amazon.com/elasticloadbalancing/latest/network/introduction.html[AWS Network Load Balancer (NLB)] when you create a link:https://kubernetes.io/docs/concepts/services-networking/service/[Kubernetes Service] of type link:https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer[LoadBalancer].

== Prerequisites

In order to be able to access exposed Ingresses and Services, you need to accordingly configure:

* Security Groups and VPC ACLs
* Route53

=== Security Group and VPS ACLs

The AWS Load Balancer Controller automatically creates a Security Group which allows access to the created Load Balancer on the specified listener port.

However, in addition its also necassary, that there is a Security Group attached to the EKS EC2 Instance which enables access for the Load Balancer to the acutual port of the Pods.
In addition also the VPC ACLs must enable access to the LoadBalancer port as well as to the internal port of a Pod. 

== Ingress

You can provide external access to Kubernetes apps by creating an link:https://kubernetes.io/docs/concepts/services-networking/ingress/[Kubernetes Ingress] resource.

The Kubernetes cluster contains a default _IngressClass_ with the name `aws-alb`.
By default, if no _ingressClassName_ is specified, all Ingress resources are managed by the deployed _AWS Load Balancer Controller_.
The default _IngressClass_ defines a group with the name `default`, which ensures, that all Ingresses are using the same _AWS ALB_.
If you need to create an Ingress which is located on another _AWS ALB_ you need to create an additional link:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/ingress_class/[IngressClass].

AWS ALB specific configuration is defined with additional Annotations which need to be added to the Ingress resource.

.The most importan annotationsa are:
[source,yaml]
----
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
alb.ingress.kubernetes.io/backend-protocol: HTTP
alb.ingress.kubernetes.io/target-type: ip
alb.ingress.kubernetes.io/healthcheck-path: /
----

The annotation `link:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#target-type[alb.ingress.kubernetes.io/target-type]: ip` specifies, that the traffic is routed directly to the individual pods. This is the prevered approach for AWS EKS, because every Pod has a reachable IP address.
The AWS Load Balancer Controller automatically adjusts the AWS target group, if a Pod is added or removed.

You find a complete overview about all allowed annotations on the link:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/[AWS Load Balancer Controller Guide].

=== HTTP

You can expose via HTTP if you add `{"HTTP": 80}` to the annotation `alb.ingress.kubernetes.io/listen-ports`.

.Ingress to expose service via HTTP, using an AWS ALB
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: ip
  name: nginx-hello-http
spec:
  rules:
  - host: nginx-hello.asyncapi.aws.uweeisele.dev
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-hello
            port:
              number: 80 
----

The host rule `nginx-hello.asyncapi.aws.uweeisele.dev` is important, because by default multiple Ingresses share the same AWS ALB. If all requests independent of the path should be forwarded to a specific target, it is also important to specify '/*' as path.

The target of an Ingress is defined as a Kubernetes service. This service must exist and be of type _ClusterIp_ and point to an group of pods. If `target-type` is `ip`, the load balancer will directly forward the requests to the individual ports, without using the service. In this case the service is only required by the AWS Load Balancer Controller to detect the actual Pods.

==== Demo

For a complete example see link:ingress-http.yaml[] and link:deployment.yaml[]

The example creates an deployment with three pods using `nginxdemos/hello:plain-text` as image.

.Deploy an example HTTP web-server to demonstrate ingress
[source,bash]
----
kubectl -n examples-$(whoami) apply -f deployment.yaml
----

The Ingress as created for host `nginx-hello.asyncapi.aws.uweeisele.dev` and path `/*`.

.Deploy HTTP Ingress for example HTTP web-server 
[source,bash]
----
 kubectl -n example-$(whoami) apply -f ingress-http.yaml
----

After the Ingress has been created, it takes some time until the AWS Load Balancer Controller created the required AWS resources.

.In order to find the created load balancer, check the status of the created Ingress resource and save the result
[source,bash]
----
kubectl -n examples-$(whoami) get ingress nginx-hello-http -o yaml
export TOOLS_LB_DNS_NAME=$(kubectl -n examples-$(whoami) get ingress nginx-hello-http -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
----

The attribute `status.loadBalancer.ingress.hostname` shows the created DNS name of the loadbalancer.

.You can use this DNS name, to make a HTTP request to your application via the created load balancer
[source,bash]
----
curl -H "Host: nginx-hello.asyncapi.aws.uweeisele.dev" http://${TOOLS_LB_DNS_NAME}
----

In order to make a request to `nginx-hello.asyncapi.aws.uweeisele.dev` you need to create a corresponding _Route53_ entry.

.You can display the created load balancer with the following aws cli query (replace the load balancer DNS name with the actual DNS name)
[source,bash]
----
aws elbv2 describe-load-balancers | jq ".LoadBalancers[] | select(.DNSName | contains(\"${TOOLS_LB_DNS_NAME}\"))"
export TOOLS_LB_ARN=$(aws elbv2 describe-load-balancers | jq -r ".LoadBalancers[] | select(.DNSName | contains(\"${TOOLS_LB_DNS_NAME}\")) | .LoadBalancerArn")
----

A load balancer can have multiple listeners. This configuration created a listener for port 80.

.List the listeners of the load balancer (replace arn with actual arn, printed by the previous command)
[source,bash]
----
aws elbv2 describe-listeners --load-balancer-arn ${TOOLS_LB_ARN}
export TOOLS_LB_LISTENER_80_ARN=$(aws elbv2 describe-listeners --load-balancer-arn ${TOOLS_LB_ARN} | jq -r ".Listeners[] | select(.Port==80) | .ListenerArn")
----

A listener can have multiple rules. This configuration created a rule for host `nginx-hello.asyncapi.aws.uweeisele.dev` and path `/*`.

.List the rules of the listener (replace arn with actual arn, printed by the previous command)
[source,bash]
----
aws elbv2 describe-rules --listener-arn ${TOOLS_LB_LISTENER_80_ARN}
export NGINX_HELLO_HTTP_TG_ARN=$(aws elbv2 describe-rules --listener-arn ${TOOLS_LB_LISTENER_80_ARN} | jq -r ".Rules[] | select(.Conditions[].Values[] | contains(\"nginx-hello\")) | .Actions[0].ForwardConfig.TargetGroups[0].TargetGroupArn")
----

If the rule matches, requests are forwared to a node defined by the assigned target group. The AWS Load Balancer Controller automatically adds the IPs of the Pods of the specified service to this target group.

.List all target IPs of the target group (replace arn with actual arn, printed by the previous command))
[source,bash]
----
aws elbv2 describe-target-health --target-group-arn ${NGINX_HELLO_HTTP_TG_ARN}
----

=== HTTPS

You can expose via HTTP if you add `{"HTTPS": 443}` to the annotation `alb.ingress.kubernetes.io/listen-ports`.

.Ingress to expose service via HTTPS, using an AWS ALB
[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/target-type: ip
  name: nginx-hello-https
spec:
  rules:
  - host: nginx-hello.asyncapi.aws.uweeisele.dev
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: nginx-hello
            port:
              name: http
----

By default, the _AWS Load Balancer Controller_ link:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/cert_discovery/[automaticaly discovers a suitable certificate] based on the defined _host_. 

If you need to explicitly specify a Certificate, you can add the annotation `link:https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/ingress/annotations/#certificate-arn[alb.ingress.kubernetes.io/certificate-arn]` and set the ARN for the required server certificate.

.Explicit definition of a certificate for the Ingress
[source,yaml]
----
alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:${ACCOUNT_ID}:certificate/${SSL_CERT_ID}
----

==== Demo

For a complete example see link:ingress-https.yaml[] and link:deployment.yaml[]

The example creates an deployment with three pods using `nginxdemos/hello:plain-text` as image.

.Deploy an example HTTP web-server to demonstrate ingress
[source,bash]
----
kubectl -n examples-$(whoami) apply -f deployment.yaml
----

The Ingress as created for host `nginx-hello.asyncapi.aws.uweeisele.dev` and path `/*`.

.Deploy HTTPS Ingress for example HTTP web-server 
[source,bash]
----
 kubectl -n example-$(whoami) apply -f ingress-https.yaml
----

After the Ingress has been created, it takes some time until the AWS Load Balancer Controller created the required AWS resources.

.In order to find the created load balancer, check the status of the created Ingress resource:
[source,bash]
----
kubectl -n examples-$(whoami) get ingress nginx-hello-https -o yaml
export TOOLS_LB_DNS_NAME=$(kubectl -n examples-$(whoami) get ingress nginx-hello-https -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
----

The attribute `status.loadBalancer.ingress.hostname` shows the created DNS name of the loadbalancer.
This sould be the same load balancer which is used for the HTTP example, because the Ingress group is the same.

.Get Ip address of load balancer
[source,bash]
----
dig ${TOOLS_LB_DNS_NAME}
export TOOLS_LB_IP=$(dig +short ${TOOLS_LB_DNS_NAME} | tail -n1)
----

Now you can explicitly map the load balancer ip to the expected host name of the service via _--resolve_ command line parameter of curl and send the request.
This is required, because also the SNI is checked, which is always set to the actuall host of the Url.

.You can use this DNS name, to make a HTTPS request to your application via the created load balancer
[source,bash]
----
curl --resolve nginx-hello.asyncapi.aws.uweeisele.dev:443:${TOOLS_LB_IP} https://nginx-hello.asyncapi.aws.uweeisele.dev
----

In order to make a request to `nginx-hello.asyncapi.aws.uweeisele.dev` you need to create a corresponding _Route53_ entry.
