= EKS

Ensure you have the required link:required-iam-policy.json[IAM permissions].

== Apply Terraform

[source,bash]
----
terraform init -backend-config="profile=tu-dev-ueisele"
----

[source,bash]
----
terraform apply --var "profile=tu-dev-ueisele"
----

== Save Outputs to Variables

[source,bash]
----
export ACCOUNT_ID="$(terraform output --raw account-id)"
export EKS_NODE_GROUP_ROLE_ARN="$(terraform output --raw eks-node-group-role-arn)"
export EKS_FARGATE_PROFILE_ROLE_ARN="$(terraform output --raw eks-fargate-profile-role-arn)"
export K8SADMIN_ROLE_ARN="$(terraform output --raw ks8admin-role-arn)"
export K8SADMIN_ASSUMEROLE_POLICY_ARN="$(terraform output --raw ks8admin-assumerole-policy-arn)"
export K8SADMIN_GROUP_ARN="$(terraform output --raw ks8admin-group-arn)"
----

== Update Kubeconfig

[source,bash]
----
aws eks --region eu-central-1 --profile tu-dev-ueisele update-kubeconfig --name showcase-eks
----

In order to run this command, `eks:DescribeCluster` permission is required.

== K8S Permissions

The user which created the EKS cluster is automatically authorized to access the cluster.

Other users must be authorized explicitely. How to do this is described at link:../k8s/README.adoc[../k8s/README.adoc] in the section `EKS IAM Auth Controller`.

In order to be able to become an admin, a user or group must have the `${K8SADMIN_ASSUMEROLE_POLICY_ARN}` attached.
The group `${K8SADMIN_GROUP_ARN}` has the `${K8SADMIN_ASSUMEROLE_POLICY_ARN}` already assigned. Every user, which is in this group is able to assume the `${K8SADMIN_ROLE_ARN}` role. 

If you add the following snippets to your `~/.aws/config` and `~/.aws/credentials` files, the use `awsuser` assumes the `${K8SADMIN_ROLE_ARN}` role if profile `k8sadmin` is used. A prerequisite is, that user `awsuser` has the `${K8SADMIN_ASSUMEROLE_POLICY_ARN}` policy assigned.

[source,bash]
----
mkdir -p ~/.aws

cat << EOF >> ~/.aws/config
[profile k8sadmin]
region = eu-central-1
role_arn=${K8SADMIN_ROLE_ARN}
source_profile=awsuser
EOF
----

[source,bash]
----
cat << EOF >> ~/.aws/credentials
[awsuser]
aws_access_key_id=${AWS_ACCESS_KEY_ID}
aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}
EOF
----

Also see: https://www.eksworkshop.com/beginner/091_iam-groups/test-cluster-access/

== Guides

* https://www.padok.fr/en/blog/aws-eks-cluster-terraform
* https://learn.hashicorp.com/tutorials/terraform/eks
* https://learnk8s.io/terraform-eks