= AWS Directory Service (AD)

https://aws.amazon.com/de/blogs/networking-and-content-delivery/integrating-your-directory-services-dns-resolution-with-amazon-route-53-resolvers/

== Apply Terraform

IMPORTANT: Requires at least two private subnets in different availability zones! By default LDAP instances are deployed to one subnet in `eu-central-1a` and one subnet in `eu-central-1b`.

[source,bash]
----
terraform init -backend-config="profile=${SHOWCASE_AWS_PROFILE}"
----

[source,bash]
----
terraform apply --var "profile=${SHOWCASE_AWS_PROFILE}"
----

Determine LDAP IDs:

[source,bash]
----
export LOCAL_LDAP_ID=$(terraform output --raw local_ldap_id)
export LOCAL_LDAP_NAME=$(terraform output --raw local_ldap_name)
export REMOTE_LDAP_ID=$(terraform output --raw remote_ldap_id)
export REMOTE_LDAP_NAME=$(terraform output --raw remote_ldap_name)
----

== Verify LDAP and Kerberos

=== Deploy Verification Pod

.Create namespace for the verification
[source,bash]
----
export NS_EXAMPLES=examples-$(whoami)
kubectl create ns ${NS_EXAMPLES}
----

.Determine LDAP username and password
[source,bash]
----
export LOCAL_LDAP_USERNAME=$(terraform output --raw local_ldap_username)
export LOCAL_LDAP_PASSWORD=$(terraform output --raw local_ldap_password)
export REMOTE_LDAP_USERNAME=$(terraform output --raw remote_ldap_username)
export REMOTE_LDAP_PASSWORD=$(terraform output --raw remote_ldap_password)
----

.Use that manifest to create the Pod
[source,bash]
----
envsubst < verify/ldaptools.yaml | kubectl -n ${NS_EXAMPLES} apply -f -
----

.Once that Pod is running, you can exec into the pod
[source,bash]
----
kubectl -n ${NS_EXAMPLES} exec -it $(kubectl -n ${NS_EXAMPLES} get pods -l app.kubernetes.io/name=ldaptools -o name) bash
----

.Finally, after you are done, remove the Pod
[source,bash]
----
envsubst < verify/ldaptools.yaml | kubectl -n ${NS_EXAMPLES} delete -f -
----

=== DNS Resolution

.Check if the DNS resolution for the LDAP domain ada.letuscode.xyz works
[source,bash]
----
> nslookup ada.letuscode.xyz
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
Name:   ada.letuscode.xyz
Address: 10.0.3.5
Name:   ada.letuscode.xyz
Address: 10.0.4.55
----

.Check if the DNS reverse lookup for the domain servers works
[source,bash]
----
> nslookup 10.0.3.5
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
5.3.0.10.in-addr.arpa   name = win-8sgn1ju6kut.ada.letuscode.xyz
5.3.0.10.in-addr.arpa   name = ada.letuscode.xyz

> nslookup 10.0.4.55
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
55.4.0.10.in-addr.arpa  name = win-0lu0jt0n3fk.ada.letuscode.xyz
55.4.0.10.in-addr.arpa  name = ada.letuscode.xyz
----

.Query the domain controllers for ada.letuscode.xyz
[source,bash]
----
> nslookup -type=srv _ldap._tcp.dc._msdcs.ada.letuscode.xyz
Server:         172.20.0.10
Address:        172.20.0.10:53

Non-authoritative answer:
_ldap._tcp.dc._msdcs.ada.letuscode.xyz  service = 0 100 389 win-8sgn1ju6kut.ada.letuscode.xyz
_ldap._tcp.dc._msdcs.ada.letuscode.xyz  service = 0 100 389 win-0lu0jt0n3fk.ada.letuscode.xyz
----

=== LDAP Queries Simple Auth

.Search ldap of domain ada.letuscode.xyz
[source,bash]
----
ldapsearch -x -H ldap://ada.letuscode.xyz -b 'dc=ada,dc=letuscode,dc=xyz' -D ${LOCAL_LDAP_USERNAME} -w ${LOCAL_LDAP_PASSWORD}
----

=== LDAP Queries Kerberos Auth

Lets prepare for Kerberos authentication. First the realm configuration must be added to the [/etc/krb5.conf](verify/krb5.conf) file:

```bash
cat > /etc/krb5.conf << EOF
[libdefaults]
        default_realm = ADA.LETUSCODE.XYZ
        rdns = false
        
        kdc_timesync = 0
        ccache_type = 4
        forwardable = true
        proxiable = true

[realms]
        ADA.LETUSCODE.XYZ = {
                kdc = ada.letuscode.xyz
                admin_server = ada.letuscode.xyz
                default_domain = ada.letuscode.xyz
        }
        COM.CODELABS.DEV = {
                kdc = com.codelabs.dev
                admin_server = com.codelabs.dev
                default_domain = com.codelabs.dev
        }

[domain_realm]
        .ada.letuscode.xyz = ADA.LETUSCODE.XYZ
        ada.letuscode.xyz = ADA.LETUSCODE.XYZ
        .com.codelabs.dev = COM.CODELABS.DEV
        com.codelabs.dev = COM.CODELABS.DEV
EOF
```

Now we can login with the command line tool `kinit` using the `ADA.LETUSCODE.XYZ` realm.

[source,bash]
----
export KRB5CCNAME=/tmp/admin.ada.letuscode.xyz.cc.tmp
echo ${LOCAL_LDAP_PASSWORD} | kinit -c ${KRB5CCNAME} Admin@ADA.LETUSCODE.XYZ
----

Show the current login with `klist`:

[source,bash]
----
> klist
Ticket cache: FILE:/tmp/admin.ada.letuscode.xyz.cc.tmp
Default principal: Admin@ADA.LETUSCODE.XYZ

Valid starting     Expires            Service principal
02/09/22 08:05:54  02/09/22 18:05:54  krbtgt/ADA.LETUSCODE.XYZ@ADA.LETUSCODE.XYZ
----

Execute `ldapsearch` with Kerberos authentication (using the previously authenticated user) and query domain `ada.letuscode.xyz`:

[source,bash]
----
ldapsearch -H ldap://ada.letuscode.xyz -Y GSSAPI -b 'dc=ada,dc=letuscode,dc=xyz' -R ADA.LETUSCODE.XYZ
----

==== Troubleshooting

Unfortunately, sometimes, the following error is returned:

----
SASL/GSSAPI authentication started
ldap_sasl_interactive_bind_s: Local error (-2)
        additional info: SASL(-1): generic failure: GSSAPI Error: Unspecified GSS failure.  Minor code may provide more information (Server not found in Kerberos database)
----

It looks like, the reason is, that Kerberos executed an reverse DNS lookup on an IP address returned by an DNS query for `ada.letuscode.xyz`. This reverse DNS request sometimes returns the hostname of the Domain controller, or the domain name itself as first entry. It only works if the hostname is the first entry, because this name is used in the Kerberos request.

You can simulate this by yourself with DNS lookup:

[source,bash]
----
nslookup ada.letuscode.xyz
----

Now take one IP and make an reverse DNS lookup:

[source,bash]
----
nslookup 10.0.4.52
----

You will recognize that sometimes the hostname is the first entry:

----
52.4.0.10.in-addr.arpa  name = win-s7kcc3309rm.ada.letuscode.xyz.
52.4.0.10.in-addr.arpa  name = ada.letuscode.xyz.
----

And sometimes the domain, which will not work:

----
52.4.0.10.in-addr.arpa  name = ada.letuscode.xyz.
52.4.0.10.in-addr.arpa  name = win-s7kcc3309rm.ada.letuscode.xyz.
----

There are two possible solutions:

* Adjust the DNS entry, in which only the actual hostname is returend
* Disable Kerberos reverse DNS lookup (I thought that `rdns=false` is doing this, but seems not the case). It seems that ldapsearch ignores this (https://lists.andrew.cmu.edu/pipermail/cyrus-sasl/2014-July/002736.html and https://www.openldap.org/lists/openldap-bugs/201507/msg00061.html).

== Create Trust Relationship

We want to create trust relation ship between the local domain (ada.letuscode.xyz) and the remote domain (com.codelabs.dev). 
The goal is, that user on the remote domain (com.codelabs.dev) can authenticate on the local domain (ada.letuscode.xyz).
In order to achieve this, an _outgoing_ trust must be created on the local domain (ada.letuscode.xyz) and an _incoming_ trust on the remote domain (com.codelabs.dev).

Unfortunately, the creation of trust relationship is not supported by Terraform until now: https://github.com/hashicorp/terraform-provider-aws/issues/11901

Required security groups are created by the Terraform script (see https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_tutorial_setup_trust_prepare_mad_between_2_managed_ad_domains.html)

.Trust directions
----
local -- one-way: outgoing --> remote
remote <-- one-way: incoming -- local
----

.Local (ada.letuscode.xyz) Trust Relationship
----
Trust type: Forest trust
Existing or new remote domain: com.codelabs.dev # the remote domain
Trust password: your_trust_password # the same password must be used when setting up the trust relationship on the remote domain.
Trust direction: One-way: outgoing # users in the remote domain can access resources in this domain
Conditional forwarders: [10.0.3.202, 10.0.4.51] # ips of the domain controllers of the remote domain
----

.Remote (com.codelabs.dev) Trust Relationship
----
Trust type: Forest trust
Existing or new remote domain: ada.letuscode.xyz # the local domain
Trust password: your_trust_password # the same password must be used when setting up the trust relationship on the local domain.
Trust direction: One-way: incoming # users in this domain can access resources in the local domain.
Conditional forwarders: [10.0.4.52, 10.0.3.119] # ips of the domain controllers of the local domain
----

=== References

* https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_setup_trust.html
* https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_tutorial_setup_trust_between_2_managed_ad_domains.html

== Verify Trust Relationship

=== On Linux with Ldapsearch and Kerberos

Exec into a newly deployed instance of the ldaptools pod and follow the setup required for Kerberos authentication.

Instead of login to `ADA.LETUSCODE.XYZ`, we now login to the realm `COM.CODELABS.DEV` with `kinit`.

[source,bash]
----
export KRB5CCNAME=/tmp/admin.com.codelabs.dev.cc.tmp
echo ${REMOTE_LDAP_PASSWORD} | kinit -c ${KRB5CCNAME} Admin@COM.CODELABS.DEV
----

Show the current login with `klist`:

----
Ticket cache: FILE:/tmp/admin.com.codelabs.dev.cc.tmp
Default principal: Admin@COM.CODELABS.DEV

Valid starting     Expires            Service principal
02/09/22 21:57:18  02/10/22 07:57:18  krbtgt/COM.CODELABS.DEV@COM.CODELABS.DEV
----

Execute `ldapsearch` with Kerberos authentication (using the previously authenticated user) and query domain `com.codelabs.dev`:

[source,bash]
----
ldapsearch -H ldap://com.codelabs.dev -Y GSSAPI -b 'dc=com,dc=codelabs,dc=dev' -R COM.CODELABS.DEV
----

If you execute `klist` again, you see, that also an login to a domain controller of `com.codelabs.dev` happend:

----
Ticket cache: FILE:/tmp/admin.com.codelabs.dev.cc.tmp
Default principal: Admin@COM.CODELABS.DEV

Valid starting     Expires            Service principal
02/09/22 21:57:18  02/10/22 07:57:18  krbtgt/COM.CODELABS.DEV@COM.CODELABS.DEV
02/09/22 21:59:19  02/10/22 07:57:18  ldap/win-i4nq6d8gegm.com.codelabs.dev@COM.CODELABS.DEV
----

Now, execute `ldapsearch` with Kerberos authentication and query domain `ada.letuscode.xyz`:

[source,bash]
----
ldapsearch -H ldap://ada.letuscode.xyz -Y GSSAPI -b 'dc=ada,dc=letuscode,dc=xyz' -R COM.CODELABS.DEV
----

This command uses the `admin` user which has been authenticated by `com.codelabs.dev`.

If you now execute `klist` again, you will see, that also an login for `ada.letuscode.xyz` exists.

----
Ticket cache: FILE:/tmp/admin.com.codelabs.dev.cc.tmp
Default principal: Admin@COM.CODELABS.DEV

Valid starting     Expires            Service principal
02/09/22 21:57:18  02/10/22 07:57:18  krbtgt/COM.CODELABS.DEV@COM.CODELABS.DEV
02/09/22 21:59:19  02/10/22 07:57:18  ldap/win-i4nq6d8gegm.com.codelabs.dev@COM.CODELABS.DEV
02/09/22 22:01:43  02/10/22 07:57:18  krbtgt/ADA.LETUSCODE.XYZ@COM.CODELABS.DEV
02/09/22 22:01:43  02/10/22 07:57:18  ldap/win-hljpgj485cu.ada.letuscode.xyz@ADA.LETUSCODE.XYZ
----

You can logout with the `kdestroy` command

=== On Windows with Login

Provision Windows EC2 instances with link:../ec2-windows[../ec2-windows], connect to the Windows instance which is assigned to domain `ada.letuscode.xyz` and login with user `Admin@ada.letuscode.xyz`.

Before you can login with users from domain `com.codelabs.dev`, the corresponding users must be added to the `AWS Delegated Administrators` group with the `Active Directory Users and Computers` tool (see https://www.youtube.com/watch?v=iLxc8XaMpno).

  * Open properties of the `AWS Delegated Administrators` group
  * Navigate to `members` and click on `Add`
  * Select `com.codelabs.dev` as location
  * Write `admin` in the `Enter the object name` field and click on `Check Names`
  * You will be asked for an user with permissions on domain `com.codelabs.dev`. The reason for this is, that it is only a one-way trust. Use `com\admin` as user and its corresponding password.
  * Click on `Ok` to add the user

Log out from the Windows EC2 instance and login again with the `admin` user of domain `com.codelabs.dev`:

Adding each user individually to the group is not practical. In order to simplify this global groups can be used which are known in both domains (see https://ss64.com/nt/syntax-groups.html)