ARG CONFLUENT_VERSION
FROM confluentinc/cp-kafkacat:${CONFLUENT_VERSION}
LABEL maintainer="Uwe Eisele <code@uweeisele.eu>"

USER root

RUN microdnf install -y cyrus-sasl cyrus-sasl-gssapi \
    && microdnf clean all \
    && rm -rf /tmp/*
